services:
  client:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - go-network
  goapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - go-network
    secrets:
      - db-password
    
  db:
    image: mysql:9.4.0-oracle
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_DATABASE: example
      MYSQL_USER: kareem
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - go-network

networks:
  go-network:
volumes:
  db-data:
secrets:
  db-password:
    file: ./backend/db-password

