---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer-sa
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-deployer-role
  namespace: production
rules:
- apiGroups: ["", "apps", "extensions", "networking.k8s.io"] # Add other necessary API groups
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-deployer-rolebinding
  namespace: production
subjects:
- kind: ServiceAccount
  name: jenkins-deployer-sa
  namespace: production
roleRef:
  kind: Role
  name: helm-deployer-role
  apiGroup: rbac.authorization.k8s.io